//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationGPV.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NhaKho
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NhaKho()
        {
            this.SanPhams = new HashSet<SanPham>();
            this.VitriSuas = new HashSet<VitriSua>();
        }
    
        public int ID_NhaKho { get; set; }
        public Nullable<int> SoTang { get; set; }
        public Nullable<int> SoHang { get; set; }
        public Nullable<int> SoCot { get; set; }
        public string Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SanPham> SanPhams { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VitriSua> VitriSuas { get; set; }
    }
}
